Import required libraries

In [1]:
import pandas as pd

Read data and rename headers

In [2]:
df = pd.read_csv('data/FIFA_World_Cup.csv', header=None, names=["league", "season", "team", "players_used", "age", "possession", 
    "matches_played", "starts", "minutes", "90s_played", 
    "goals", "assists", "goals_plus_assists", "goals_minus_penalty", 
    "penalty_goals", "penalty_attempts", "yellow_cards", "red_cards", 
    "expected_goals", "non_penalty_xG", "expected_assists", 
    "non_penalty_xG_plus_xA", "progressive_carries", "progressive_passes", 
    "goals_per_90", "assists_per_90", "goals_plus_assists_per_90", 
    "goals_minus_penalty_per_90", "goals_plus_assists_minus_penalty_per_90", 
    "xG_per_90", "xA_per_90", "xG_plus_xA_per_90", "non_penalty_xG_per_90", 
    "non_penalty_xG_plus_xA_per_90", "url"])

In [3]:
df

,league,season,team,players_used,age,possession,matches_played,starts,minutes,90s_played,...,assists_per_90,goals_plus_assists_per_90,goals_minus_penalty_per_90,goals_plus_assists_minus_penalty_per_90,xG_per_90,xA_per_90,xG_plus_xA_per_90,non_penalty_xG_per_90,non_penalty_xG_plus_xA_per_90,url
0,NaN,NaN,NaN,players_used,Age,Poss,Playing Time,Playing Time,Playing Time,Playing Time,...,Per 90 Minutes,Per 90 Minutes,Per 90 Minutes,Per 90 Minutes,Per 90 Minutes,Per 90 Minutes,Per 90 Minutes,Per 90 Minutes,Per 90 Minutes,url
1,NaN,NaN,NaN,NaN,NaN,NaN,MP,Starts,Min,90s,...,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,NaN
2,league,season,team,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,INT-World Cup,1930,Argentina,21,24.3,NaN,5,55,450,5.0,...,NaN,NaN,3.6,NaN,NaN,NaN,NaN,NaN,NaN,/en/squads/f9fddd6e/1930/Argentina-Men-Stats
4,INT-World Cup,1930,Belgium,13,23.4,NaN,2,22,180,2.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,/en/squads/361422b9/1930/Belgium-Men-Stats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,INT-World Cup,2022,Switzerland,24,27.6,49.0,4,44,360,4.0,...,1.0,2.25,1.25,2.25,1.37,0.91,2.28,1.37,2.28,/en/squads/81021a70/2022/Switzerland-Men-Stats
488,INT-World Cup,2022,Tunisia,21,26.9,44.3,3,33,270,3.0,...,0.33,0.67,0.33,0.67,0.77,0.64,1.41,0.77,1.41,/en/squads/a7c7562a/2022/Tunisia-Men-Stats
489,INT-World Cup,2022,United States,20,24.5,53.0,4,44,360,4.0,...,0.75,1.5,0.75,1.5,1.01,0.87,1.89,1.01,1.89,/en/squads/0f66725b/2022/United-States-Men-Stats
490,INT-World Cup,2022,Uruguay,19,27.6,48.7,3,33,270,3.0,...,0.33,1.0,0.67,1.0,1.23,0.92,2.15,1.23,2.15,/en/squads/870e020f/2022/Uruguay-Men-Stats
491,INT-World Cup,2022,Wales,18,26.8,46.7,3,33,270,3.0,...,0.0,0.33,0.0,0.0,0.91,0.59,1.49,0.65,1.23,/en/squads/b1bbcad3/2022/Wales-Men-Stats

Remove the first and second row as both are the header names

In [4]:
df = df.copy()
df = df.iloc[3:]

Dropping columns based on observation

In [5]:
df.drop(columns=['league', 'assists','goals_plus_assists','expected_assists','non_penalty_xG_plus_xA','assists_per_90','goals_plus_assists_per_90',
                 'xA_per_90','xG_plus_xA_per_90','goals_plus_assists_minus_penalty_per_90','non_penalty_xG_plus_xA_per_90','url','league'], inplace = True)

Changing West Germany into Germany

In [6]:
df['team'] = df['team'].replace('West Germany', 'Germany')
print(df['team'].unique())

['Argentina' 'Belgium' 'Bolivia' 'Brazil' 'Chile' 'France' 'Mexico'
 'Paraguay' 'Peru' 'Romania' 'United States' 'Uruguay' 'Yugoslavia'
 'Austria' 'Czechoslovakia' 'Egypt' 'Germany' 'Hungary' 'Italy'
 'Netherlands' 'Spain' 'Sweden' 'Switzerland' 'Cuba' 'Dutch East Indies'
 'Norway' 'Poland' 'England' 'Korea Republic' 'Scotland' 'Türkiye'
 'Northern Ireland' 'Soviet Union' 'Wales' 'Bulgaria' 'Colombia'
 'Korea DPR' 'Portugal' 'El Salvador' 'Israel' 'Morocco' 'Australia'
 'Germany DR' 'Haiti' 'Zaire' 'IR Iran' 'Tunisia' 'Algeria' 'Cameroon'
 'Honduras' 'Kuwait' 'New Zealand' 'Canada' 'Denmark' 'Iraq' 'Costa Rica'
 'Rep. of Ireland' 'UAE' 'Greece' 'Nigeria' 'Russia' 'Saudi Arabia'
 'Croatia' 'Jamaica' 'Japan' 'South Africa' 'China PR' 'Ecuador' 'Senegal'
 'Slovenia' 'Angola' 'Czechia' "Côte d'Ivoire" 'Ghana'
 'Serbia & Montenegro' 'Togo' 'Trin & Tobago' 'Ukraine' 'Serbia'
 'Slovakia' "Bosnia & Herz'na" 'Iceland' 'Panama' 'Qatar']

Convert several columns to numerical columns

In [7]:
df['season'] = pd.to_numeric(df['season'], errors='coerce')
cols = df.columns[3:24]
df[cols] = df[cols].apply(pd.to_numeric, errors ='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 3 to 491
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   season                      489 non-null    int64
 1   team                        489 non-null    object
 2   players_used                489 non-null    object
 3   age                         489 non-null    float64
 4   possession                  96 non-null     float64
 5   matches_played              489 non-null    int64
 6   starts                      489 non-null    int64
 7   minutes                     489 non-null    int64
 8   90s_played                  489 non-null    float64
 9   goals                       489 non-null    int64
 10  goals_minus_penalty         489 non-null    int64
 11  penalty_goals               489 non-null    int64
 12  penalty_attempts            224 non-null    float64
 13  yellow_cards                489 non-null    int64
 14  red_cards                   489 non-null    int64
 15  expected_goals              64 non-null     float64
 16  non_penalty_xG              64 non-null     float64
 17  progressive_carries         64 non-null     float64
 18  progressive_passes          64 non-null     float64
 19  goals_per_90                489 non-null    float64
 20  goals_minus_penalty_per_90  489 non-null    float64
 21  xG_per_90                   64 non-null     float64
 22  non_penalty_xG_per_90       64 non-null     float64
dtypes: float64(12), int64(9), object(2)
memory usage: 88.0+ KB

Add a column for the winners of each season

In [8]:
world_cup_winners = world_cup_winners = {
    1930: 'Uruguay',
    1934: 'Italy',
    1938: 'Italy',
    1950: 'Uruguay',
    1954: 'Germany',
    1958: 'Brazil',
    1962: 'Brazil',
    1966: 'England',
    1970: 'Brazil',
    1974: 'Germany',
    1978: 'Argentina',
    1982: 'Italy',
    1986: 'Argentina',
    1990: 'Germany',
    1994: 'Brazil',
    1998: 'France',
    2002: 'Brazil',
    2006: 'Italy',
    2010: 'Spain',
    2014: 'Germany',
    2018: 'France',
    2022: 'Argentina'
}


df['world_cup_winner'] = df.apply(lambda row : 1 if row['team'] == world_cup_winners.get(row['season']) else 0, axis = 1)

Add a continent column for each team

In [9]:
countries = pd.read_csv('data/countryContinent.csv', encoding = 'latin1')
countries = countries[['country', 'continent']]

Changing some of the country names

In [10]:
country_rep = {
    'Bolivia (Plurinational State of)':'Bolivia',
    'United States of America':'United States',
    'Macedonia (the former Yugoslav Republic of)':'Yugoslavia',
    'Czech Republic':'Czechoslovakia',
    'Indonesia':'Dutch East Indies',
    'Turkey':'Türkiye',
    'United Kingdom of Great Britain and Northern Ireland' : 'England',
    'Korea (Republic of)': 'Korea Republic',
    "Korea (Democratic People's Republic of)" : 'Korea DPR', 
    'Iran (Islamic Republic of)' : 'IR Iran',
    'Ireland' : 'Rep. of Ireland',
    'United Arab Emirates' : 'UAE',
    'Russian Federation' : 'Russia',
    'China' : 'China PR',
    'Bosnia and Herzegovina' : "Bosnia & Herz'na"
}

countries['country'] = countries['country'].replace(country_rep)

Merge to the dataframe

In [11]:
df = df.merge(countries, left_on = 'team', right_on = 'country').drop(columns = 'country')

Dealing with missing values

In [12]:
df.isnull().sum()

season                          0
team                            0
players_used                    0
age                             0
possession                    369
matches_played                  0
starts                          0
minutes                         0
90s_played                      0
goals                           0
goals_minus_penalty             0
penalty_goals                   0
penalty_attempts              245
yellow_cards                    0
red_cards                       0
expected_goals                401
non_penalty_xG                401
progressive_carries           401
progressive_passes            401
goals_per_90                    0
goals_minus_penalty_per_90      0
xG_per_90                     401
non_penalty_xG_per_90         401
world_cup_winner                0
continent                       0
dtype: int64

Threshold for missing values: drop columns with more than 50% missing values

In [13]:
threshold = 0.50
df_cleaned = df.dropna(thresh=int(df.shape[0] * (1 - threshold)), axis=1)

Checking if all the missing values have been dealt with

In [14]:
df_cleaned.isnull().sum()

season                        0
team                          0
players_used                  0
age                           0
matches_played                0
starts                        0
minutes                       0
90s_played                    0
goals                         0
goals_minus_penalty           0
penalty_goals                 0
yellow_cards                  0
red_cards                     0
goals_per_90                  0
goals_minus_penalty_per_90    0
world_cup_winner              0
continent                     0
dtype: int64

In [15]:
df_cleaned

,season,team,players_used,age,matches_played,starts,minutes,90s_played,goals,goals_minus_penalty,penalty_goals,yellow_cards,red_cards,goals_per_90,goals_minus_penalty_per_90,world_cup_winner,continent
0,1930,Argentina,21,24.3,5,55,450,5.0,18,18,0,0,0,3.60,3.60,0,Americas
1,1930,Belgium,13,23.4,2,22,180,2.0,0,0,0,0,0,0.00,0.00,0,Europe
2,1930,Bolivia,13,24.3,2,22,180,2.0,0,0,0,0,0,0.00,0.00,0,Americas
3,1930,Brazil,17,24.2,2,22,180,2.0,5,5,0,0,0,2.50,2.50,0,Americas
4,1930,Chile,16,25.7,3,33,270,3.0,4,4,0,0,0,1.33,1.33,0,Americas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,2022,Spain,21,25.5,4,44,390,4.3,9,8,1,2,0,2.08,1.85,0,Europe
460,2022,Switzerland,24,27.6,4,44,360,4.0,5,5,0,9,0,1.25,1.25,0,Europe
461,2022,Tunisia,21,26.9,3,33,270,3.0,1,1,0,5,0,0.33,0.33,0,Africa
462,2022,United States,20,24.5,4,44,360,4.0,3,3,0,5,0,0.75,0.75,0,Americas
463,2022,Uruguay,19,27.6,3,33,270,3.0,2,2,0,8,0,0.67,0.67,0,Americas

In [16]:
df_cleaned.to_csv('data/FIFA_World_Cup_Tidy.csv', index = False)